#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: mcr.microsoft.com/dotnet/core/sdk:3.1
pipelines:
  default:
    - step:
        name: Build
        caches:
          - dotnetcore
        script: 
          - export SOLUTION_NAME= DDDNetCore.csproj        
          - export CONFIGURATION=Release
          - dotnet restore SOLUTION_NAME.sln
          - dotnet build --no-restore $SOLUTION_NAME.sln --configuration $CONFIGURATION
          - dotnet test --no-build $SOLUTION_NAME.sln
