# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test-GestArm_API:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          working_directory: Backend/GestArm_API/GestArm/
          name: Build
          command: |
            dotnet build
      - run:
          working_directory: Backend/GestArm_API/GestArmTestes/UnitTesting
          name: Test
          command: |
            dotnet build
            dotnet test
        

  build-and-test-GestLog_API:
    docker:
       - image: cimg/node:current
    steps:
      - checkout
      - run:
          working_directory: Backend/GestLogistica_API/GestLogistica
          name: install-npm
          command:  |
           npm innit --yes
           npm install --save
      - save_cache:
          key: dependency-cache-{{ checksum "Backend/GestLogistica_API/GestLogistica/package.json" }}
          paths:
            - Backend/GestLogistica_API/GestLogistica/node_modules
      - run:
          working_directory: Backend/GestLogistica_API/GestLogistica
          name : Build
          command: |
            npm run build
      - run:
         working_directory: Backend/GestLogistica_API/GestLogistica
         name : Test
         command: |
          npm run test
      - run:
          working_directory: Backend/GestLogistica_API/GestLogistica
          name : Coverage
          command: |
            npm run coverage        

workflows:
  development:
    jobs:
      - build-and-test-GestArm_API
      - build-and-test-GestLog_API